# Generated by Django 4.1.7 on 2024-08-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0011_tovarvariation'),
        ('carts', '0002_alter_cart_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herbs.tovarvariation'),
        ),
    ]
