# Generated by Django 4.1.7 on 2023-11-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/group/')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbs.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photo/tovar/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Url')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='herbs.group')),
            ],
            options={
                'verbose_name': 'tovar',
                'verbose_name_plural': 'tovar',
            },
        ),
    ]
