# Generated by Django 4.1.7 on 2024-04-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0002_sale_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tovar',
            options={'ordering': ('id',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
