# Generated by Django 4.1.7 on 2024-07-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_alter_tovar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
