# Generated by Django 4.1.7 on 2024-07-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0004_tovar_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount in percentage', max_digits=4),
        ),
        migrations.AddField(
            model_name='tovar',
            name='sale_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='herbs.sale_category'),
        ),
        migrations.DeleteModel(
            name='Sale_tovar',
        ),
    ]
