# Generated by Django 4.1.7 on 2024-07-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0005_tovar_discount_tovar_sale_category_delete_sale_tovar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='sale_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='herbs.sale_category'),
        ),
    ]
