# Generated by Django 4.1.7 on 2024-08-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0006_alter_tovar_sale_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/tovar/')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='herbs.tovar')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'ordering': ('id',),
            },
        ),
    ]
