# Generated by Django 4.1.7 on 2024-08-16 10:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0007_tovarphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
