# Generated by Django 4.1.7 on 2024-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0009_alter_tovar_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='group',
        ),
        migrations.AddField(
            model_name='tovar',
            name='group',
            field=models.ManyToManyField(related_name='tovars', to='herbs.group'),
        ),
    ]
