# Generated by Django 4.1.7 on 2024-08-31 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0010_remove_tovar_group_tovar_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='herbs.tovar')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
            },
        ),
    ]
