# Generated by Django 4.1.7 on 2024-09-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0011_tovarvariation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='discount',
        ),
        migrations.AddField(
            model_name='tovar',
            name='tovar_variations',
            field=models.ManyToManyField(blank=True, related_name='tovars', to='herbs.tovarvariation'),
        ),
        migrations.AddField(
            model_name='tovarvariation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount in percentage', max_digits=4),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
