# Generated by Django 4.1.7 on 2024-09-16 17:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0012_remove_tovar_discount_tovar_tovar_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='active_ingredients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='condition_of_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='ingredients',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='main_purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='product_benefits',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='region_of_manufacture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tovar',
            name='usage_instructions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='tovar_variations',
            field=models.ManyToManyField(blank=True, default=1, related_name='tovars', to='herbs.tovarvariation'),
        ),
    ]
